name: flutter_login
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  #  path: ../../packages/flutter_bloc
  user_repository:
    path: user_repository
  equatable: ^1.1.1
  url_launcher: ^5.4.2
  email_validator: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^5.1.0
    #path: ../../packages/bloc_test
  mockito: ^4.0.0

flutter:
  uses-material-design: true
